apiVersion: v1
appVersion: "latest"
description: Enshrouded - Enshrouded Dedicated Server
name: enshrouded
version: 0.0.2
icon: https://cdn.cloudflare.steamstatic.com/steam/apps/1203620/header.jpg
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
maintainers:
  - name: Logan Saso
    email: logansaso@gmail.com
