apiVersion: v1
appVersion: "latest"
description: hkmp - Hollow Knight Multi Player
name: hkmp
version: 0.0.2
icon: https://gamepedia.cursecdn.com/hkmp_gamepedia/c/c4/hkmp.png
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
maintainers:
  - name: Logan Saso
    email: logansaso@gmail.com
